name: PR comment
# This workflow is triggered after the linting action is complete

on:
  workflow_run:
    workflows: ["Long arrays in translations"]
    types: [completed]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      actions: write
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: on artifact
        id: artifact
        uses: marocchino/on_artifact@v1
        with:
          name: En_GBLocalise-logs

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: En_GBLocalise-class ${{ steps.artifact.outputs.pr_number }}
          number: ${{ steps.artifact.outputs.pr_number }}
          message: |
           The following translation files contain the long arrays syntax on ${{ steps.artifact.outputs.pr_sha }}
            ```
            ${{ steps.artifact.outputs.long-arrays_result }}
            ```
            Affecting ${{ steps.artifact.outputs.long-arrays_files_affected }} files in ${{ steps.artifact.outputs.long-arrays_languagepacks_affectedf }} language packs.
